services:
    - type: web
      name: vizitka-app
      runtime: docker
      dockerfilePath: ./Dockerfile
      dockerContext: .
      envVars:
          - key: APP_ENV
            value: production
          - key: APP_DEBUG
            value: 'false'
          - key: APP_URL
            value: https://vizitka-app.onrender.com
          - key: APP_KEY
            generateValue: true
          - key: ASSET_URL
            value: https://vizitka-app.onrender.com
          - key: DB_CONNECTION
            value: pgsql
          - key: DATABASE_URL
            fromDatabase:
                name: vizitka-db
                property: connectionString
          - key: SESSION_DRIVER
            value: cookie
          - key: CACHE_STORE
            value: database
          - key: QUEUE_CONNECTION
            value: database
          - key: BCRYPT_ROUNDS
            value: '12'
          - key: LOG_CHANNEL
            value: stderr
          - key: MAIL_MAILER
            value: log
          - key: SEED_ON_DEPLOY
            value: 'true'
      region: oregon
      plan: free
      healthCheckPath: /

databases:
    - name: vizitka-db
      databaseName: vizitka
      user: vizitka
      plan: free
      region: oregon
      postgresMajorVersion: '17'
